config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"

  get 'stripe/oauth', to: 'users#stripe_sign_up'
  devise_for :users
  root to: 'pages#home'

# JOBS

  resources :jobs do
    resources :favourites, only: [:create, :destroy]
    resources :shifts, except: :show do
      resources :orders, only: [:create]
      resources :requests, except: [:show]
      get 'requests/confirmation', to: 'requests#confirmation'
    end
  end
  get 'jobs/:id/close', to: 'jobs#close', as: :job_close
  post 'jobs/sort_pay', to: 'jobs#order_by_pay'
  get 'job/order_by_pay', to: 'jobs#order_by_pay', as: :sort_pay
  get 'job/filter', to: 'jobs#filter', as: :job_filter

# Payments

  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  get '/confirmation_page', to: 'pages#confirmation_page'

# Shifts

  patch '/shifts/close', to: 'shifts#close_shifts', as: :close_shifts
  get 'shifts/:id/users/:user_id/offers/new', to: 'offers#new', as: :new_shift_offer
  post 'shifts/:id/users/:user_id/offers', to: 'offers#create', as: :create_shift_offer
  post 'shifts/:shift_id/reviews', to: 'reviews#create', as: :shift_reviews
  resources :shifts, only: :show

# Offers

  resources :offers, only: :show
  patch 'offers/:id/accept_offer', to: 'shifts#accept_offer', as: 'accept_offer'

# Requests

  resources :requests, only: [:show] do
    resources :chats, only: [:create]
  end
  patch 'requests/:id/accept_request', to: 'shifts#accept_request', as: 'accept_request'

# Applications

  get '/active_applications', to: 'requests#active_applications', as: :active_applications

# Users

  get 'users/:id/offers/select', to: 'offers#select', as: :new_user_offer
  resources :users, only: [:edit, :update]
  get 'user/search', to: 'users#filter', as: :users_filter
  get 'user/sort_score', to: 'users#order_by_score', as: :users_sort_score

  get '/employees', to: 'users#index', as: :users

# Reviews

  get '/reviews', to: 'reviews#review_dashboard', as: :review_dashboard

# Dashboard

  get 'dashboard_employer/closed_jobs', to: 'jobs#closed_jobs', as: :closed_jobs
  get 'dashboard_employer/listed_jobs', to: 'jobs#listed_jobs', as: :listed_jobs
  get '/dashboard_employer', to: 'pages#dashboard_employer'

  get '/dashboard', to: 'pages#dashboard'
  get 'dashboard/pending', to: 'requests#pending_requests', as: 'pending_requests'
  get 'dashboard/upcoming', to: 'shifts#upcoming_shifts', as: 'upcoming_shifts'
  get 'dashboard/historic', to: 'shifts#historic_shifts', as: 'historic_shifts'
  get 'dashboard/favourites', to: 'favourites#index', as: 'favourites'
  get '/dashboard/chats/:id', to: 'chats#inbox_show', as: :dashboard_chat


# Chat

  resources :chats, except: :create do
    resources :messages
  end
  get '/inbox', to: 'chats#inbox', as: :inbox


  # authenticate :user, lambda { |u| u.admin } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  # include searchkick and elasticsearch
  searchkick word_middle: [:title, :venue], filterable: [:sectors]
  Job.reindex

  belongs_to :user
  has_many :favourites
  has_many :sector_joiners
  has_many :sectors, through: :sector_joiners
  has_many :shifts, dependent: :destroy
  has_many :reviews, through: :shifts

  validates :title, presence: true, length: { in: 2..100 }
  validates :description, presence: true, length: { maximum: 200 }
  validates :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  scope :search_by_sector, ->(ids) { joins(:sector_joiners).merge(SectorJoiner.where(sector_id: ids.map(&:to_i))) }


  def relevant_shifts(min_price, max_price, lower_start_date, higher_start_date)
    if min_price && lower_start_date
      new_shifts = shifts.reject { |shift| (shift.start_time < lower_start_date) || (shift.start_time > higher_start_date) }.reject { |shift| (shift.price_cents < min_price) || (shift.price_cents > max_price) }
    elsif min_price
      new_shifts = shifts.reject { |shift| (shift.price_cents < min_price) || (shift.price_cents > max_price) }
    elsif lower_start_date
      new_shifts = shifts.reject { |shift| (shift.start_time < lower_start_date) || (shift.start_time > higher_start_date) }
    else
      new_shifts = shifts
    end

    new_shifts.reject { |shift| shift.completed || shift.user || Time.parse(shift.start_time) < Time.now }
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :close, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :filter, :order_by_pay]

  @@jobs
  @@search_term = ""

  def index
    @request = Request.new
    @favourite = Favourite.new
    @@jobs = policy_scope(Job).order(created_at: :desc)
    @jobs= @@jobs
    if @jobs
      @markers = @jobs.map do |job|
        {
          lat: job.latitude,
          lng: job.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { job: job })
        }
      end
    end
  end

  def filter
    if params[:search][:query] &.== @@search_term
      @jobs = @@jobs
    else
      @jobs = apply_search
    end
    authorize @jobs
    filter_pay
    filter_time
    filter_sector

    respond_to do |format|
      format.js
    end
  end

  def filter_title_venue
    @jobs = apply_search
    authorize @jobs
    respond_to do |format|
      format.html { redirect_to jobs_path }
      format.js
    end
  end

  def order_by_pay
    @jobs = @@jobs
    authorize @jobs
    @jobs = @jobs.sort_by(&:pay).reverse
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @shift = Shift.new
    @request = Request.new
    @review = Review.new

    if @jobs
      @markers = @job.map do |job|
        {
          lat: job.latitude,
          lng: job.longitude
        }
      end
    end
  end

  def new
    @job = Job.new
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    sector_ids = params[:job][:sector_ids].drop(1)
    @sectors = sector_ids.map do |element|
      Sector.find(element)
    end
    @job.sectors = @sectors
    @job.user = current_user
    authorize @job
    if @job.save
      sleep 3
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @job.update(job_params)
    if @job.save
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  def close
    @job.done = true
    authorize @job
    @job.save
    redirect_to dashboard_employer_path(@job.user)
  end

  def destroy
    @job.destroy
    redirect_to jobs_path
  end

  def closed_jobs
    @jobs = current_user.jobs.where({done: true})
    authorize @jobs
  end

  def listed_jobs
    @jobs = current_user.jobs.where({done: nil})
    authorize @jobs
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :location, :summary, :sector_ids, :venue)
  end

  def set_job
    @job = Job.find(params[:id])
    authorize @job
  end

  def apply_search
    @@jobs = policy_scope(Job).order(created_at: :desc)
    if params[:search][:query]
      @@search_term == params[:search][:query]
      @@jobs = @@jobs.search "#{params[:search][:query]}", match: :word_middle unless params.dig(:search, :query).blank?
    end
    @@jobs
  end

  def filter_pay
    if params[:my_range]
      @lower_pay = params[:my_range].split(";").first.to_i * 100
      @higher_pay = params[:my_range].split(";").last.to_i * 100

      @jobs = @jobs.select do |job|
        job.shifts.pluck(:price_cents).any? { |pay| (pay > @lower_pay) && (pay < @higher_pay) } &&
          job.shifts.select { |shift| (shift.price_cents > @lower_pay) && (shift.price_cents < @higher_pay) }.any? { |shift| !shift.completed }
      end
    end
    @jobs
  end

  def filter_sector
    if params[:search][:sectors] && params[:search][:sectors].reject(&:blank?)
      sectors = params[:search][:sectors].reject(&:blank?).map do |id|
        Sector.find(id)
      end
      unless sectors.empty?
        @jobs = @jobs.select {|job| job.sectors.any? { |sector| sectors.include?(sector)}}
      end
    end
    @jobs
  end

  def filter_time
    if params[:start_time].present?
      lower_start_time = params[:start_time].split(";").first.to_i / 1000 + 3600
      higher_start_time = params[:start_time].split(";").last.to_i / 1000 + 3600
      base_date = Time.parse("1 January 1970")
      @lower_start_date = base_date + lower_start_time
      @higher_start_date = base_date + higher_start_time

      @jobs = @jobs.select do |job|
        job.shifts.pluck(:start_time).any? { |start| start > @lower_start_date && start < @higher_start_date }
      end
    end
    @jobs
  end



end

app/views/jobs/_info_window.html.erb
<div class="info-window p-2">
  <h5><%= job.title %></h5>
  <i class="fas fa-user-clock card-icon"></i>
  <p><%= job.location.scan(/.*.+?(?=, )/).first %></p>
  <button type="button" class="btn btn-map" data-toggle="modal" data-target="#showJob<%=job.id%>">
    Learn more
  </button>
</div>

app/views/jobs/closed_jobs.html.erb
<% page = "closed_jobs" %>

<div class="wrapper">
  <%= render 'pages/shared/employer_dashboard_sidebar', page: page %>
  <div class="container pt-3">
    <div class="m-2 d-flex justify-content-between align-items-center">
      <h3 class="pt-3">Closed Jobs</h3>
      <%= link_to "Create Job", new_job_path, class: "btn btn-ghost" %>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Job</th>
          <th scope="col">Shifts</th>
          <th scope="col">Applications</th>
          <th scope="col">Details</th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>

          <% active_shifts = job.shifts.select { |shift| Time.parse(shift.start_time) > Time.now && !shift.user} %>
          <% num_shifts = active_shifts.length  %>
          <% num_requests = 0 %>

          <% active_shifts.each do  |shift|  %>
            <% num_requests += shift.requests.count %>
          <% end %>

          <% if num_shifts == 0 || num_requests == 0 %>
            <% c = "table-success" %>
          <% elsif num_shifts > 2 && num_requests > 2 %>
            <% c = "table-danger" %>
          <% elsif num_shifts > 2 || num_requests > 2 %>
            <% c = "table-warning" %>
          <% end %>

         <tr class="<%= c %>">
            <th scope="row"><%= job.title %></th>
            <td><%= num_shifts %> unstaffed</td>
            <td><%= num_requests %> pending applications </td>
            <td><%= link_to 'View Details', job_path(job), class: "btn btn-bw" %></td>
          </tr>

        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/filter.js.erb
var filterResults = document.getElementById('jobs-section');

function clearHtml() {
  filterResults.innerHTML = ""
}

function addHtml(html) {
  filterResults.insertAdjacentHTML('beforeend', html);
}

clearHtml()

clearHtml()
<% unless @jobs.empty? %>
  <% @jobs.each do |job|%>
    <% num_shifts = job.shifts.select { |shift| Time.parse(shift.start_time) > Time.now && !shift.user}.length  %>
    <% unless num_shifts <= 0 %>
      addHtml("<%= j render 'jobs/shared/job-details-modal', favourite: @favourite, job: job, num_shifts: num_shifts %>")
    <% end %>
  <% end %>
  addHtml("<a href='/jobs' class='btn btn-bw d-block d-sm-none my-3' id='display_all_jobs'>Display all</a>")

<% else %>
  addHtml("Sorry, no jobs matched your criteria - <a class='inline-link' href='/jobs'>clear filters</a>")
<% end %>

var colls = document.querySelectorAll(".collapsible");

colls.forEach((coll) => {
  coll.addEventListener("click", (e) => {
    e.currentTarget.classList.toggle("active")
    var content = e.currentTarget.nextElementSibling;
    if (e.currentTarget.classList.contains("active")){
      content.style.height = 0;

    } else {
      content.style.height = content.scrollHeight + "px";

    }
  });
})

app/views/jobs/index.html.erb
<div class="targeter d-none">
  <% if params[:search] %>
    <% if params[:search][:sectors] %>
      data-sectors="<%= params[:search][:sectors].reject(&:empty?) %>"
    <% end %>
  <% end %>
  <% if @lower_start_date %>
    data-startyear="<%= @lower_start_date.year %>"
    data-startmonth="<%= @lower_start_date.month %>"
    data-startday="<%= @lower_start_date.day %>"
  <% end %>
  <% if @higher_start_date %>
    data-endyear="<%= @higher_start_date.year %>"
    data-endmonth="<%= @higher_start_date.month %>"
    data-endday="<%= @higher_start_date.day %>"
  <% end %>
</div>

<div class="row mx-0">
  <!--  Search content  -->
  <div class="content-index col-12 col-lg-7">
    <div class="container">
      <div class="pt-3 border-bottom">
        <h1 class="my-3">Available Jobs</h1>
      </div>
      <%= simple_form_for :search, url: job_filter_path, method: :get, remote: true do |f| %>
        <div class="form-group form-inline pt-3 justify-content-between nowrap">
          <div class="d-flex justify-content-between align-items-center w-100" >
            <input class="form-control width-85 mr-1 pl-3 search-bar" type="text" placeholder="Job search" name="search[query]" id="search_query" value="<%= params.dig(:search, :query) %>"/>
            <div>
              <button name="button" type="submit" class="btn btn-search" style="height: 3.5rem">
                <i class="full-hidden fas fa-search"></i> <span class="mobile-hidden">Search</span>
              </button>
            </div>
          </div>
        </div>

      <div class="d-flex align-items-center">
        <div class="dropdown-toggle width-85 mb-3 btn btn-large btn-bw clickable active mr-1" id="filter-dropdown">
          Filter
        </div>
        <%= image_tag "", class: "fas fa-sort-amount-down mb-3 btn btn-large btn-plain clickable active", id: "sortDropDown", data: {toggle: 'dropdown'}, 'aria-haspopup': false, 'aria-expanded': false %>
        <div class="dropdown-box dropdown-menu dropdown-menu-right mt-3" aria-labelledby="sortDropDown">
          <%= link_to 'Pay', sort_pay_path, remote: :true, class: "dropdown-item" %>
        </div>

      </div>

      <div class="content-collapse" id="filter-form">
            <%= f.input :sectors, collection: Sector.all, label_method: :title, value_method: :id, label: false, required: false, wrapper_html: {class: "ml-0"}, input_html: { class: 'search_category mx-3', multiple: true, style: 'width: 100%', value: "" } %>
            <%= f.input :price_cents, label: "Filter by pay/h", required: false, wrapper_html: {class: "ml-1 pr-2"},
              input_html: { class: 'js-range-slider',
              type: 'text',
              name: 'my_range',
              value: "",
              'data-type': "double",
              'data-min': "5",
              'data-max': "50",
              'data-from': "#{params[:my_range].split(';').first if params[:my_range]}",
              'data-to': "#{params[:my_range].split(';').last if params[:my_range]}",
              'data-grid': "true",
              'data-keyboard': "true",
              'data-skin': "round",
              'data-prefix': "£"
            } %>

            <%= f.input :start_time, label: "Filter by date", required: false,
            wrapper_html: {class: "mx-5"},
                input_html: { class: 'js-range-slider2',
                type: 'text',
                name: 'start_time',
                value: "",
                'data-type': "double",
                'data-skin': "round"
              } %>
            <div>
              <button name="button" type="submit" class="float-right mb-2 btn btn-search " style="height: 42px; width: 128px;">
                <i class="fas fa-filter"></i> Filter
              </button>
              <%= link_to 'Display all', jobs_path, class: 'btn btn-bw mb-2' %>
            </div>
        <% end %>
      </div>
      <div id="jobs-section">
        <% unless @jobs.empty? %>
          <% @jobs.each do |job|%>
            <% num_shifts = job.shifts.select { |shift| Time.parse(shift.start_time) > Time.now && !shift.user}.length  %>
            <% unless num_shifts <= 0 %>
              <%= render 'jobs/shared/job-details-modal', favourite: @favourite, job: job, num_shifts: num_shifts %>
            <% end %>
          <% end %>
          <%= link_to 'Display all', jobs_path, class: 'btn btn-bw d-block d-sm-none my-3', id: 'display_all_jobs' %>
        <% else %>
          <%= 'Sorry, no jobs matched your criteria' %> - <%= link_to 'clear filters', jobs_path, class: "inline-link" %>
        <% end %>
      </div>
    </div> <!-- End of container -->
  </div> <!-- End of search content -->
<!--   Map box -->
  <div class="col-5 col-lg-5 d-none d-lg-block d-xl-block">
    <div
      id="map"
      style=" position: sticky;
      top: 65px;
      bottom: 0;
      display: block;
      width: 100%;
      height: 92vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div> <!-- End of map -->
</div>

app/views/jobs/listed_jobs.html.erb
<% page = "listed_jobs" %>
<div class="wrapper">
  <%= render 'pages/shared/employer_dashboard_sidebar', page: page %>
  <div class="container pt-3">
    <div class="m-2 d-flex justify-content-between align-items-center">
      <h3 class="pt-3">Listed Jobs</h3>
      <%= link_to "Create Job", new_job_path, class: "btn btn-sign-up" %>
    </div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Job</th>
          <th scope="col">Shifts</th>
          <th scope="col">Applications</th>
          <th scope="col">Details</th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
          <% active_shifts = job.shifts.select { |shift| Time.parse(shift.start_time) > Time.now && !shift.user} %>
          <% num_shifts = active_shifts.length  %>
          <% num_requests = 0 %>

          <% active_shifts.each do  |shift|  %>
            <% num_requests += shift.requests.count %>
          <% end %>
          <tr class="">
            <th scope="row"><%= job.title %></th>
            <td><%= num_shifts %> unstaffed</td>
            <td><%= num_requests %> pending applications </td>
            <td><%= link_to 'View Details', job_path(job), class: "btn btn-bw" %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div> <!-- End of container -->
</div> <!-- End of wrapper -->

app/views/jobs/new.html.erb
<div class="container py-3">
  <h1>New Job</h1>
  <%= simple_form_for @job do |f| %>
    <%= f.input :title, error: 'Title must be between 2 and 30 characters' %>
    <%= f.input :summary, label: 'Company Name' %>
    <%= f.input :description, as: :text, error: 'Must have a description' %>
    <%= f.input :location, error: 'Must have a location' %>
    <%= f.association :sectors, label_method: :title, value_method: :id, input_html: { class: 'sector-picker' } %>
    <%= f.button :submit, "Create Job", class: "btn btn-bw" %>
  <% end %>
</div>

app/views/jobs/order_by_pay.js.erb
var searchResults = document.getElementById('jobs-section');

function clearHtml() {
  searchResults.innerHTML = ""
}

function addHtml(html) {
  searchResults.insertAdjacentHTML('beforeend', html);
}

clearHtml()
<% unless @jobs.empty? %>
  <% @jobs.each do |job|%>
    <% num_shifts = job.shifts.select { |shift| Time.parse(shift.start_time) > Time.now && !shift.user}.length  %>
    <% unless num_shifts <= 0 %>
      addHtml("<%= j render 'jobs/shared/job-details-modal', favourite: @favourite, job: job, num_shifts: num_shifts %>")
    <% end %>
  <% end %>
  addHtml("<a href='/jobs' class='btn btn-bw d-block d-sm-none my-3' id='display_all_jobs'>Display all</a>")

<% else %>
  addHtml("Sorry, no jobs matched your criteria - <a class='inline-link' href='/jobs'>clear filters</a>")
<% end %>

var colls = document.querySelectorAll(".collapsible");

colls.forEach((coll) => {
  coll.addEventListener("click", (e) => {
    e.currentTarget.classList.toggle("active");
    var content = e.currentTarget.nextElementSibling;
    if (e.currentTarget.classList.contains("active")){
      content.style.height = 0;
    } else {
      content.style.height = content.scrollHeight + "px";
    }
  });
})

app/views/jobs/show.html.erb
<% page = "listed_jobs" %>

<div class="wrapper">
  <%= render 'pages/shared/employer_dashboard_sidebar', page: page %>
  <div class="container py-3">
    <div class="d-flex justify-content-between">
      <div>
        <div class="py-1">
          <h1><%= @job.title %></h1>
          <h6>Description:</h6>
          <p><%= @job.description %></p>
        </div>
        <h6>Categories:</h6>
        <% @job.sectors.each do |sector| %>
          <div class="row px-3">
            <p class="btn btn-show"><%= sector.title %></p>
          </div>
        <% end %>
      </div>

      <div>
        <%= render 'shifts/shared/create-shift', shift: @shift, modal_button: "Create Shift"%>
        <%= render 'jobs/shared/edit-job', open_modal: "", modal_title: "Edit This Job", button_text: "Save Changes"%>
      </div>
    </div>
    <h2>Upcoming Shifts</h2>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Shift</th>
          <th scope="col">Hourly Rate</th>
          <th scope="col">Total Pay</th>
          <th scope="col">Applications</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @job.shifts.order(start_time: :desc).each do |shift| %>
          <% unless Time.parse(shift.start_time) < Time.now %>
            <% if shift.user %>
              <tr class="table-success">
            <% else %>
              <tr>
            <% end %>
              <th scope="row"><%= Time.parse(shift.start_time).strftime("%e %b") %>: <%= Time.parse(shift.start_time).strftime("%H:%M") %> to <%= Time.parse(shift.end_time).strftime("%H:%M") %></th>
              <td>Hourly Price: <%= humanized_money_with_symbol(shift.price) %></td>
              <td>Total Pay: <%= number_to_currency(shift.total_pay, unit: "£") %></td>
              <% if shift.user %>
                <td>

                    <span><i class="fas fa-check"></i>   <%= "Booked: #{shift.user.first_name}" %></span>

                </td>
                <% chat = shift.requests.where(user: shift.user).first.chat %>
                <td><%= link_to "Message #{shift.user.first_name}", chat_path(chat), class: "btn btn-bw" %></td>
              <% else %>
                <td><%= render 'requests/shared/view-requests-modal', shift: shift %></td>
                <td><%= render 'shifts/edit-shift', shift: shift, modal_button: "" %></td>
              <% end %>

            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <h2>Past Shifts</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Shift</th>
          <th scope="col">Hourly Rate</th>
          <th scope="col">Total Pay</th>
          <th scope="col">Review</th>
          <th scope="col">Payment</th>
        </tr>
      </thead>
      <tbody>
        <% @job.shifts.order(start_time: :desc).each do |shift| %>
          <% if Time.parse(shift.start_time) < Time.now && shift.user %>
            <% if shift.order %>
              <% if shift.order.state = "paid" %>
                <tr class="table-success">
              <% end %>
            <% else %>
              <tr>
            <% end %>
              <th scope="row"><%= Time.parse(shift.start_time).strftime("%e %b") %>: <%= Time.parse(shift.start_time).strftime("%H:%M") %> to <%= Time.parse(shift.end_time).strftime("%H:%M") %></th>
              <td>Hourly Price: <%= humanized_money_with_symbol(shift.price) %></td>
              <td>Total Pay: <%= number_to_currency(shift.total_pay, unit: "£") %></td>

              <% unless shift.reviews.any? { |review| review.user == shift.user} %>
                <td><%= render 'reviews/shared/create-review-modal', shift: shift, review_target: shift.user %></td>
              <% else %>
                <td>

                    <i class="fas fa-check"></i>   <%= "Reviewed: #{shift.user.first_name}" %>

                </td>
              <% end %>
              <% if shift.order %>
                <% if shift.order.state = "paid" %>
                  <td><i type="" class="btn btn-paid">🎉 PAID 🎉</i></td>
                <% end %>
              <% else %>
                <td>
                  <%= form_tag job_shift_orders_path(@job, shift) do %>
                    <%= hidden_field_tag 'shift_id', @shift.id %>
                    <%= hidden_field_tag 'job_id', @job.id %>
                    <%= submit_tag 'Pay', class: 'btn btn-bw' %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <% if policy(@job).edit? %>
      <%= link_to 'Back', dashboard_employer_path(@job.user), class: 'btn btn-ghost' %>
      <%= link_to "Close Job Listing", job_close_path(@job), class: "btn btn-ghost"  %>
    <% end %>

  </div>
</div>