config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"

  get 'stripe/oauth', to: 'users#stripe_sign_up'
  devise_for :users
  root to: 'pages#home'

# JOBS

  resources :jobs do
    resources :favourites, only: [:create, :destroy]
    resources :shifts, except: :show do
      resources :orders, only: [:create]
      resources :requests, except: [:show]
      get 'requests/confirmation', to: 'requests#confirmation'
    end
  end
  get 'jobs/:id/close', to: 'jobs#close', as: :job_close
  post 'jobs/sort_pay', to: 'jobs#order_by_pay'
  get 'job/order_by_pay', to: 'jobs#order_by_pay', as: :sort_pay
  get 'job/filter', to: 'jobs#filter', as: :job_filter

# Payments

  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  get '/confirmation_page', to: 'pages#confirmation_page'

# Shifts

  patch '/shifts/close', to: 'shifts#close_shifts', as: :close_shifts
  get 'shifts/:id/users/:user_id/offers/new', to: 'offers#new', as: :new_shift_offer
  post 'shifts/:id/users/:user_id/offers', to: 'offers#create', as: :create_shift_offer
  post 'shifts/:shift_id/reviews', to: 'reviews#create', as: :shift_reviews
  resources :shifts, only: :show

# Offers

  resources :offers, only: :show
  patch 'offers/:id/accept_offer', to: 'shifts#accept_offer', as: 'accept_offer'

# Requests

  resources :requests, only: [:show] do
    resources :chats, only: [:create]
  end
  patch 'requests/:id/accept_request', to: 'shifts#accept_request', as: 'accept_request'

# Applications

  get '/active_applications', to: 'requests#active_applications', as: :active_applications

# Users

  get 'users/:id/offers/select', to: 'offers#select', as: :new_user_offer
  resources :users, only: [:edit, :update]
  get 'user/search', to: 'users#filter', as: :users_filter
  get 'user/sort_score', to: 'users#order_by_score', as: :users_sort_score

  get '/employees', to: 'users#index', as: :users

# Reviews

  get '/reviews', to: 'reviews#review_dashboard', as: :review_dashboard

# Dashboard

  get 'dashboard_employer/closed_jobs', to: 'jobs#closed_jobs', as: :closed_jobs
  get 'dashboard_employer/listed_jobs', to: 'jobs#listed_jobs', as: :listed_jobs
  get '/dashboard_employer', to: 'pages#dashboard_employer'

  get '/dashboard', to: 'pages#dashboard'
  get 'dashboard/pending', to: 'requests#pending_requests', as: 'pending_requests'
  get 'dashboard/upcoming', to: 'shifts#upcoming_shifts', as: 'upcoming_shifts'
  get 'dashboard/historic', to: 'shifts#historic_shifts', as: 'historic_shifts'
  get 'dashboard/favourites', to: 'favourites#index', as: 'favourites'
  get '/dashboard/chats/:id', to: 'chats#inbox_show', as: :dashboard_chat


# Chat

  resources :chats, except: :create do
    resources :messages
  end
  get '/inbox', to: 'chats#inbox', as: :inbox


  # authenticate :user, lambda { |u| u.admin } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application.html.erb
  <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#createApplication">
    <%= "Apply" %>
  </button>

  <div class="modal fade" id="createApplication" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle"><%= "New Shift" %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for [@job, @application], url: job_shift_applications_path(@job, shift) do |f| %>
              <%= f.input :content %>
              <%= f.button :submit, "Apply", class: "btn btn-flat" %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

app/views/shared/_avatar.html.erb
<% if current_user && current_user.photo.attached? %>
  <%= cl_image_tag current_user.photo.key, class: 'avatar dropdown-toggle', id: 'navbarDropdown', data: {toggle: 'dropdown'}, 'aria-haspopup': true, 'aria-expanded': false %>
<% else %>
  <%= image_tag "avatar.jpg", class: 'avatar dropdown-toggle homepage-avatar mobile-avatar', id: 'navbarDropdown', data: {toggle: 'dropdown'}, 'aria-haspopup': true, 'aria-expanded': false %>
<% end %>

<div class="dropdown-menu dropdown-box mt-3 dropdown-menu-right" aria-labelledby="navbarDropdown">
  <% if current_user %>

    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    <% if  current_user.employer %>
      <%= link_to 'Search Staff', users_path, class: "dropdown-item"  %>
    <% else %>
      <%= link_to 'Search Jobs', jobs_path, class: "dropdown-item"  %>
    <% end %>
    <%= link_to 'Dashboard', current_user.employer ? dashboard_employer_path : dashboard_path, class: "dropdown-item"  %>

    <%= link_to 'Messages', inbox_path, class: "dropdown-item" %>

  <% else %>
    <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
    <%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item" %>
  <% end %>
</div>

app/views/shared/_bottom-navbar.html.erb
<% if current_user %>
  <% messages = 0 %>
  <% current_user.chats.each do |chat| %>
    <% messages += chat.messages.select {|m| m.user != current_user && !m.read}.size %>
  <% end %>
<% end %>

<div class="d-flex justify-content-around fixed-bottom navbar navbar-bottom">

  <div class="w-20 text-center bottom-navlink" >
    <%= link_to '', root_path, class: "fas fa-home text-center bottom-navlink"  %>
  </div>

  <div class="w-20 text-center bottom-navlink">
    <% if current_user %>
      <%= link_to '', current_user.employer ? users_path : jobs_path, class: "fas fa-search text-center bottom-navlink"  %>
    <% else %>
      <%= link_to '', jobs_path, class: "fas fa-search text-center bottom-navlink"  %>
    <% end %>
  </div>

  <% if current_user %>
    <div class="w-20 bottom-navlink">
      <%= link_to '', favourites_path, class: "far fa-heart text-center bottom-navlink"  %>
    </div>

    <div class="w-20 bottom-navlink notification-container">
      <%= link_to '', inbox_path, class: "fas fa-inbox text-center bottom-navlink"  %>
      <div class="bottom-nav-notification <%= messages == 0 ? 'd-none' : ''%>"><%= messages %></div>
    </div>
  <% end %>

  <div class="w-20 bottom-navlink">
    <% if current_user %>
      <%= link_to '', current_user.employer ? dashboard_employer_path : dashboard_path, class: "far fa-id-card text-center bottom-navlink"  %>
    <% else %>
      <%= link_to '', new_user_registration_path, class: "fas fa-user-plus text-center bottom-navlink green-marker"  %>
    <% end %>
  </div>
</div>

app/views/shared/_dashboard-navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-homepage">
    <p></p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">


          <% if current_user && current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: 'avatar dropdown-toggle', id: 'navbarDropdown', data: {toggle: 'dropdown'}, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://media14.s-nbcnews.com/j/MSNBC/Components/Video/201905/tdy_news_grumpy_cat_190517_1920x1080.860;484;7;70;5.jpg", class: 'avatar dropdown-toggle', id: 'navbarDropdown', data: {toggle: 'dropdown'}, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if current_user && current_user.employer %>
          <%= link_to 'Dashboard (Employer)', dashboard_employer_path, class: "dropdown-item" %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to 'Dashboard', dashboard_path, class: "dropdown-item" %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% end %>
        <% unless current_user %>
          <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
          <%= link_to 'Sign Up', "#", class: "dropdown-item", data: {toggle: "modal", target: "#modalContactForm"} %>
        <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog signup-modal-master" role="document">
    <div class="modal-content signup-modal">
      <%= render 'devise/registrations/new' %>
    </div>
  </div>
</div>

app/views/shared/_homepage-navbar.html.erb
<div class="fixed-top d-flex justify-content-between align-items-center mobile-hidden" id="homepage-navbar">
   <%= link_to image_tag("https://res.cloudinary.com/cwhight/image/upload/v1587654447/template_t_white_qmkzcy.png"), current_user&.employer ? dashboard_employer_path : root_path, class: "p-3 t-logo", id: "white-t"  %>
   <%= link_to image_tag("https://res.cloudinary.com/cwhight/image/upload/v1587655300/template_t_blue_vuz04r.png"), current_user&.employer ? dashboard_employer_path : root_path, class: "d-none p-3 t-logo", id: "blue-t"  %>
  <% if current_user %>
    <div class="d-flex flex-column justify-content-around px-2">
      <%= render 'shared/avatar', class: 'homepage-avatar ' %>
    </div>
  <% else %>
    <div class="d-flex">
      <div class="">
        <%= link_to 'Sign in', new_user_session_path, class: "btn btn-login" %>
      </div>
      <div class="px-2">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-sign-up" %>
      </div>
    </div>
  <% end %>

</div>

<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog signup-modal-master" role="document">
    <div class="modal-content signup-modal">
      <%= render 'devise/registrations/new' %>
    </div>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_modal-form.html.erb
  <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#formModalCenter">
    <i class="far fa-edit"></i>
  </button>

  <div class="modal fade" id="formModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle"><%= "#{modal_title}" %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for @job do |f| %>
              <%= f.input :title, error: 'Title must be between 2 and 30 characters' %>
              <%= f.input :summary, label: 'Company Name' %>
              <%= f.input :description, as: :text, error: 'Must have a description' %>
              <%= f.input :location, error: 'Must have a location' %>
              <%= f.button :submit, "Create Job", class: "btn btn-flat" %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <% messages = 0 %>
  <% current_user.chats.each do |chat| %>
    <% messages += chat.messages.select {|m| m.user != current_user && !m.read}.size %>
  <% end %>
<% end %>


<div class="fixed-top d-flex justify-content-between mobile-hidden navbar-standard">
  <div class="d-flex">
    <%= link_to image_tag("https://res.cloudinary.com/dt02hu2ll/image/upload/v1575471730/template-404-logo_njqxag.png"), current_user&.employer ? users_path : root_path, class: "navbar-brand px-2 py-3"  %>
  </div>

  <div class="d-flex">
    <% if current_user %>
      <% if  current_user.employer %>
        <div class="d-flex align-items-center">
          <%= link_to "Create Job", new_job_path, class: "btn btn-sign-up" %>
        </div>
        <%= link_to 'Search Staff', users_path, class: "nav-link"  %>
      <% else %>
        <%= link_to 'Search Jobs', jobs_path, class: "nav-link"  %>
      <% end %>
      <%= link_to 'Dashboard', current_user.employer ? dashboard_employer_path : dashboard_path, class: "nav-link"  %>
      <div class="notification-container">
        <%= link_to 'Messages', inbox_path, class: "h-100 nav-link" %>
        <div class="nav-notification <%= messages == 0 ? 'd-none' : ''%>"><%= messages %></div>
      </div>
    <% end %>
    <div class="d-flex flex-column justify-content-around px-2">
      <%= render 'shared/avatar', class: 'homepage-avatar ' %>
    </div>
  </div>
</div>

app/views/shared/_request.html.erb
  <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#createRequest<%=shift.id%>">
    <%= "Apply" %>
  </button>

  <div class="modal fade" id="createRequest<%=shift.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle"><%= "Apply for Shift" %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for [job, @request], url: job_shift_requests_path(job, shift) do |f| %>
              <%= f.input :content %>
              <%= f.button :submit, "Apply", class: "btn btn-ghost" %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

app/views/shared/_review.html.erb
  <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#createReview<%=shift.id%>">
    <%= "Review #{review_target.first_name}" %>
  </button>

  <div class="modal fade" id="createReview<%=shift.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle"><%= "Review #{review_target.first_name}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="review-form">
          <%= render 'shared/review-form', shift: shift, review: @review %>
        </div>

      </div>
    </div>
  </div>

app/views/shared/_show-jobs.html.erb
<%= render 'shared/job-card', job: job, num_shifts: num_shifts, favourite: favourite %>
<div class="modal fade"  id="showJob<%=job.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-xl modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content card shadow-none">
      <div class="modal-header job-summary-header">
        <div>
            <h5 class="modal-title job-summary-title" id="exampleModalLongTitle"><%= "#{job.title}" %></h5>

          <p class="mb-0 pb-0"><%= job.summary %></p>

        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <% score_array = job.user.reviews.map { |review| review.score } %>
          <div class="mb-1 d-flex justify-content-between">
            <p>
              <strong>Employer: </strong>
              <%= "#{job.user.first_name} - " %>
              <% unless score_array.empty? %>
                <% average_score = score_array.reduce(:+).to_f / score_array.length %>
                <span ><%= average_score.round(1) %><i class="star fas fa-star"></i></span>
              <% end %>
            </p>
            <div>
              <%= cl_image_tag job.user.photo.key, class: "avatar d-inline float-right", crop: :fill if job.user.photo.attached? %>
            </div>
          </div>
          <p><i class="red-marker fas fa-map-marker-alt"></i> <%= job.location %></p>
          <p><i class="green-marker fas fa-angle-double-right"></i> <%= job.description %></p>
          <div class="dropdown">
            <% num_shifts = job.shifts.reject { |shift| shift.completed || shift.user || Time.parse(shift.start_time) < Time.now}.length  %>
            <div class="dropdown-toggle btn btn-flat collapsible active">
              View <%= job.relevant_shifts(@lower_pay, @higher_pay, @lower_start_date, @higher_start_date).count %> Available Shifts
            </div>
            <div class="content-collapse">
              <% job.relevant_shifts(@lower_pay, @higher_pay, @lower_start_date, @higher_start_date).sort_by { |shift| shift.start_time }.each do |shift| %>
                <% unless shift.user || shift.completed %>
                  <% if Time.parse(shift.start_time) > Time.now %>
                    <div class="dropdown-item message-submission">
                      <div class="p-2 border-bottom">
                        <div class="p-1 d-flex justify-content-between">
                          <p><%= Time.parse(shift&.start_time)&.strftime("%e %b") %></p>
                          <p><%= Time.parse(shift&.start_time)&.strftime("%k:%M") %> to <%= Time.parse(shift&.end_time)&.strftime("%k:%M") %></p>
                        </div>
                        <div class="p-1 d-flex justify-content-between">
                          <p><%= humanized_money_with_symbol(shift.price) %>/h</p>
                          <%= link_to "Apply", new_job_shift_request_path(job, shift), class: "btn btn-sign-up" %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_top-mobile-nav.html.erb
<div class="d-flex justify-content-between fixed-top navbar navbar-top-mobile py-1">

  <div class="" >

      <a href="#"><i class="top-navlink fas fa-align-left" id="sidebarCollapse"></i></a>


  </div>

  <div class="">

      <%#= render 'shared/avatar', class: 'homepage-avatar ' %>
      <!-- <a href="#"><i class="fas top-navlink fa-align-center dropdown-toggle top-nav-dropdown"></i></a> -->
    <%= image_tag "", class: "fas top-navlink dropdown-toggle top-nav-dropdown", id: 'navbarDropdown', data: {toggle: 'dropdown'}, 'aria-haspopup': false, 'aria-expanded': false %>



    <div class="dropdown-box dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <% if current_user %>

        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% if  current_user.employer %>
          <%= link_to 'Search Staff', users_path, class: "dropdown-item"  %>
        <% else %>
          <%= link_to 'Search Jobs', jobs_path, class: "dropdown-item"  %>
        <% end %>
        <%= link_to 'Dashboard', current_user.employer ? dashboard_employer_path : dashboard_path, class: "dropdown-item"  %>

        <%= link_to 'Messages', inbox_path, class: "dropdown-item" %>

      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item" %>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_view_applications.html.erb
  <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#viewApplications">
    <%= "View Applications" %>
  </button>

  <div class="modal fade" id="viewApplications" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle"><%= "New Shift" %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <% shift.applications.each do |app| %>
              <p><%= app.user.email %></p>
              <p><%= app.content %></p>
            <% end %>
          </div>

        </div>
      </div>
    </div>

app/views/shared/_view_requests.html.erb
  <button type="button" class="btn btn-flat my-2" data-toggle="modal" data-target="#show<%=shift.id%>">
    <% request_number = 0 %>
    <% request_number += shift.requests.select{ |request| !request.shift.user && Time.parse(request.shift.start_time) > Time.now }.size %>
    <% if request_number == 0 %>
      <p class="m-0">No applications</p>
    <% elsif request_number == 1 %>
      <p class="m-0"><%= request_number %> application</p>
    <% else  %>
      <p class="m-0"><%= request_number %> applications</p>
    <% end %>
  </button>

  <div class="modal fade" id="show<%=shift.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle"><%= "Open Applications (#{shift.requests.length})" %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">

            <% shift.requests.each do |request| %>
              <div class="card m-3 p-3">
                <% score_array = request.user.reviews.map { |review| review.score } %>
                <% unless score_array.empty? %>
                  <% average_score = score_array.reduce(:+).to_f / score_array.length %>
                    <h5 class="mb-2"><%= "#{request.user.first_name} #{request.user.surname} - " %><span ><% average_score.round.times do %><i class="star fas fa-star"></i><% end %></h5>
                <% else %>
                  <p><%= "#{request.user.first_name} #{request.user.surname}" %></p>
                  <p>Review Score: No Reviews Yet </p>
                <% end %>
                <p><%= request.content %></p>
                <%= link_to "More details >", request_path(request), class: "btn btn-flat m-1" %>
              </div>
            <% end %>
          </div>

        </div>
      </div>
    </div>