config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"

  get 'stripe/oauth', to: 'users#stripe_sign_up'
  devise_for :users
  root to: 'pages#home'

# JOBS

  resources :jobs do
    resources :favourites, only: [:create, :destroy]
    resources :shifts, except: :show do
      resources :orders, only: [:create]
      resources :requests, except: [:show]
      get 'requests/confirmation', to: 'requests#confirmation'
    end
  end
  get 'jobs/:id/close', to: 'jobs#close', as: :job_close
  post 'jobs/sort_pay', to: 'jobs#order_by_pay'
  get 'job/order_by_pay', to: 'jobs#order_by_pay', as: :sort_pay
  get 'job/filter', to: 'jobs#filter', as: :job_filter

# Payments

  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  get '/confirmation_page', to: 'pages#confirmation_page'

# Shifts

  patch '/shifts/close', to: 'shifts#close_shifts', as: :close_shifts
  get 'shifts/:id/users/:user_id/offers/new', to: 'offers#new', as: :new_shift_offer
  post 'shifts/:id/users/:user_id/offers', to: 'offers#create', as: :create_shift_offer
  post 'shifts/:shift_id/reviews', to: 'reviews#create', as: :shift_reviews
  resources :shifts, only: :show

# Offers

  resources :offers, only: :show
  patch 'offers/:id/accept_offer', to: 'shifts#accept_offer', as: 'accept_offer'

# Requests

  resources :requests, only: [:show] do
    resources :chats, only: [:create]
  end
  patch 'requests/:id/accept_request', to: 'shifts#accept_request', as: 'accept_request'

# Applications

  get '/active_applications', to: 'requests#active_applications', as: :active_applications

# Users

  get 'users/:id/offers/select', to: 'offers#select', as: :new_user_offer
  resources :users, only: [:edit, :update]
  get 'user/search', to: 'users#filter', as: :users_filter
  get 'user/sort_score', to: 'users#order_by_score', as: :users_sort_score

  get '/employees', to: 'users#index', as: :users

# Reviews

  get '/reviews', to: 'reviews#review_dashboard', as: :review_dashboard

# Dashboard

  get 'dashboard_employer/closed_jobs', to: 'jobs#closed_jobs', as: :closed_jobs
  get 'dashboard_employer/listed_jobs', to: 'jobs#listed_jobs', as: :listed_jobs
  get '/dashboard_employer', to: 'pages#dashboard_employer'

  get '/dashboard', to: 'pages#dashboard'
  get 'dashboard/pending', to: 'requests#pending_requests', as: 'pending_requests'
  get 'dashboard/upcoming', to: 'shifts#upcoming_shifts', as: 'upcoming_shifts'
  get 'dashboard/historic', to: 'shifts#historic_shifts', as: 'historic_shifts'
  get 'dashboard/favourites', to: 'favourites#index', as: 'favourites'
  get '/dashboard/chats/:id', to: 'chats#inbox_show', as: :dashboard_chat


# Chat

  resources :chats, except: :create do
    resources :messages
  end
  get '/inbox', to: 'chats#inbox', as: :inbox


  # authenticate :user, lambda { |u| u.admin } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :shift
  has_one :chat
  has_one :offer
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show]

  def show
    authorize @request
    @chat = @request.chat
    @message = Message.new
    # mark_as_read(@chat)
  end

  def new
    @shift = Shift.find(params[:shift_id])
    @job = Job.find(params[:job_id])

    @request = Request.new

    @markers = [{
      lat: @job.latitude,
      lng: @job.longitude
    }]

    authorize @request
  end

  # def confirmation
  #   @shift = Shift.find(params[:shift_id])
  #   @job = Job.find(params[:job_id])

  #   @request = Request.new

  #   @markers = [{
  #     lat: @job.latitude,
  #     lng: @job.longitude
  #   }]

  #   authorize @request
  # end

  def create
    @request = Request.new(request_params)
    authorize @request
    @request.user = current_user
    @request.completed = false
    @request.shift = Shift.find(params[:shift_id])
    if @request.save
      @chat = Chat.new
      @chat.request = @request
      @chat.employee = @request.user
      @chat.employer = @request.shift.job.user
      if @chat.save
        @message = Message.new
        @message.chat = @chat
        @message.content = @request.content
        @message.user = @request.user
        if @message.save
          sleep 3
          redirect_to dashboard_path(current_user)
        end
      end
    else
      render :new
    end
  end

  def active_applications
    authorize Request
  end

  def pending_requests
    @requests = current_user.requests
    authorize @requests
  end

  private

  def request_params
    params.require(:request).permit(:title, :content, :completed, :shift_id)
  end

  def set_request
    @request = Request.find(params[:id])
  end
end

app/views/requests/active_applications.html.erb
<% page = "active" %>
<% applications = current_user.chats.reject {|ch| ch.request.shift.user || Time.parse(ch.request.shift.start_time) < Time.now }.size %>

<div class="wrapper">
  <%= render 'pages/shared/employer_dashboard_sidebar', page: page %>
  <div class="container px-2 pt-3">
    <div>
      <h3 class="pt-3">Active Applications</h3>
      <p>Manage your job applications here - you currently have <%= applications %> applications </p>

    </div>
    <div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Job</th>
            <th scope="col">Shift</th>
            <th scope="col">Applicant</th>
            <th scope="col">Messages</th>
          </tr>
        </thead>
      <tbody>


        <% current_user.chats.each do |chat| %>
          <% request = chat.request %>
          <% unless request.shift.user || Time.parse(request.shift.start_time) < Time.now %>

            <tr>
              <th scope="row"><%= request.shift.job.title %></th>
              <td><strong><%= Time.parse(request.shift.start_time).strftime("%e %b") %>:</strong> <%= Time.parse(request.shift.start_time).strftime("%H:%M") %> to <%= Time.parse(request.shift.end_time).strftime("%H:%M") %></td>
              <td><%= request.user.first_name %></td>
              <% if request.chat %>
                <td><%= link_to 'View Application', request_path(request), class: "btn btn-bw" %></td>
              <% else %>
                <td></td>
              <% end %>
            </tr>
          <% end %>

        <% end %>
      </tbody>
      </table>
    </div>

  </div>
</div>

app/views/requests/confirmation.html.erb
<div class="container confirmation-page">
  <h2><i class="fas fa-arrow-right"></i> Your application for <%= @job.title %> at <%= @job.venue %></h2><br>
  <div class="row">
    <div class="col-sm-6">
      <div>
        <%= render '/users/shared/profile-card', user: current_user, profile: true %>
      </div>
      <div
        id="map"
        style="
        display: block;
        height: 40vh;
        width: 100%;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        class="card"
        >
      </div>
    </div>

      <div class="card col-sm-6 job-summary">
        <div class="row justify-content-between">
          <div class="col-12 summary-text">
            <h3>Job Summary</h3>
            <p><b>Hiring Manager:</b> <%= @job.user.first_name %> <%= @job.user.surname %></p>
            <p><%= @job.description %></p>
            <p><b>Job Title: </b><%= @job.title %></p>
            <p><b>Location: </b><%= @shift.job.location %></p>
            <p><b>Shift Available: </b><%= @shift.start_time %> - <%= @shift.end_time %></p>
            <p><b>Hourly Rate: </b><%= humanized_money_with_symbol(@shift.price)%></p>
            <div id="applyForm" class="col-12 modal-body message-submission">
              <h5>Submit your message to <%= @job.user.first_name %></h5>
              <%= simple_form_for  [@job, @request], url: job_shift_requests_path(@job, @shift) do |f| %>
                <%= f.input :content, label_html: { class: "content-label" }, input_html: { class: "confirm-page-box" } %>
                <%= f.button :submit, "Send Application", class: "btn btn-ghost", id: "employee-apply-sweetalert" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="container confirmation-page">
  <h2 class="mt-2"><i class="fas fa-arrow-right"></i> Your application for <%= @job.title %> at <%= @job.venue %></h2><br>
  <div class="row">
    <% score_array = @job.user.reviews.map { |review| review.score } %>
      <div class="col-12  col-md-6">
        <div class="d-flex justify-content-between">
          <div class="m-2 p-3 card summary-text">
            <div class="d-flex justify-content-between">

              <h3>Job Summary</h3>
              <%= cl_image_tag @job.user.photo.key, class: "avatar d-inline float-right", crop: :fill if @job.user.photo.attached? %>
            </div>
            <p>
              <b>Hiring Manager:</b> <%= @job.user.first_name %> <%= @job.user.surname %>
              <% unless score_array.empty? %>
                <% average_score = score_array.reduce(:+).to_f / score_array.length %>
                <span > - <%= average_score.round(1) %> <i class="star fas fa-star"></i></span>
              <% end %>
            </p>
            <p><%= @job.description %></p>
            <p><b><i class="red-marker fas fa-map-marker-alt"></i> Location: </b><%= @shift.job.location %></p>
            <p><b><i class="blue-icon fas fa-calendar"></i> Shift Available: </b><%= Time.parse(@shift&.start_time)&.strftime("%e %b") %>, <%= Time.parse(@shift&.start_time)&.strftime("%k:%M") %> to <%= Time.parse(@shift&.end_time)&.strftime("%k:%M") %></p>
            <p><b><i class="star fas fa-coins"></i> Hourly Rate: </b> <%= humanized_money_with_symbol(@shift.price)%></p>
            <p><b><i class="pink-icon fas fa-piggy-bank"></i> Total Pay:</b> <%= number_to_currency(@shift.total_pay, unit: "£") %></p>
            <div id="applyForm" class="col-12 modal-body message-submission">
              <h5>Submit your message to <%= @job.user.first_name %></h5>
              <%= simple_form_for  [@job, @request], url: job_shift_requests_path(@job, @shift) do |f| %>
                <%= f.input :content, label_html: { class: "content-label" }, input_html: { class: "confirm-page-box" } %>
                <%= f.button :submit, "Send Application", class: "btn btn-bw", id: "employee-apply-sweetalert" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <div class="col-12 col-md-6">
      <div id="">
        <%= render '/users/shared/profile-card', user: current_user, profile: true %>
      </div>
      <div
        id="map"
        style="
        display: block;
        height: 40vh;
        "
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        class="card m-2 mb-4"
        >
      </div>
    </div>
  </div>
</div>

app/views/requests/new.js.erb
function refreshForm(innerHTML) {
  const newApplication = document.getElementbyId('applyForm');
  newApplication.innerHTML = innerHTML;
}

<% if @request.valid? %>
  window.location.href = "/dashboard"
<% else %>
  var form = document.querySelector("#review-form")
  refreshForm("<%= j render 'reviews/shared/review-form', shift: @shift, review: @review %>")
<% end %>

app/views/requests/pending_requests.html.erb
<% page = "pending" %>
<% pending_requests = 0 %>
<% current_user.requests.each do |request| %>
  <% unless request.shift.user || Time.parse(request.shift.start_time) < Time.now %>
    <% pending_requests += 1 %>
  <% end %>
<% end %>

<div class="wrapper">
  <%= render 'pages/shared/employee_dashboard_sidebar', page: page %>
  <div class="container px-2 py-3">
    <div>
      <h3 class="pt-3">Active Applications</h3>
      <p>Manage your job applications here - you currently have <%= pending_requests %> applications </p>

    </div>
    <div>
      <table class="table table-hover" style="max-width: 100%">
        <thead>
          <tr>

            <th scope="col">Shift</th>
            <th scope="col">Employer</th>
            <th scope="col">Messages</th>
          </tr>
        </thead>
        <tbody>
          <% @requests.order(created_at: :desc).each do |request| %>
            <% unless request.shift.user || Time.parse(request.shift.start_time) < Time.now%>

               <tr>
                  <th scope="row">
                    <p><%= request.shift.job.title %></p>
                    <p><%= Time.parse(request.shift.start_time).strftime("%e %b") %> - <%= Time.parse(request.shift.start_time).strftime("%H:%M") %> to <%= Time.parse(request.shift.end_time).strftime("%H:%M") %></p>
                  </th>
                  <td><%= request.shift.job.user.first_name %></td>
                  <% if request.offer %>
                    <td><%= link_to 'View Offer', offer_path(request.offer), class: 'btn btn-bw' %></td>
                  <% else %>
                    <td><%= link_to 'View Messages', chat_path(request.chat), class: 'btn btn-bw' %></td>
                  <% end %>
                </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/requests/show.html.erb
<div class="wrapper">
    <%= render 'pages/shared/employer_dashboard_sidebar', page: "" %>
    <div class="container py-3">


    <div class="d-flex justify-content-between align-items-start m-3">
      <h1>Request from <%= @request.user.first_name.capitalize %></h1>
      <div><i class="fas fa-arrow-right"></i>  <%= link_to "View Job Listing", job_path(@request.shift.job), class: 'inbox-link' %></div>

    </div>
    <div class="row mb-3">
      <% user = @request.user %>
      <div class="col-12 col-md-6">
        <div class="h-100">
          <div class="soft-card shadow-sm">
            <%= render 'users/shared/profile-card', user: @request.user %>
          </div>
          <div class="p-3 mt-3 soft-card shadow-sm">
            <h2><%= user.first_name %>'s Reviews</h2>
            <div class="reviews border-top">

              <% if user.reviews.any? %>
                <% user.reviews.each do |review| %>
                 <%= render 'reviews/shared/review-card', review: review %>
                <% end %>
              <% else %>
                <p>No reviews yet</p>
              <% end %>
            </div>
          </div>
        </div>

      </div>

      <div class="col-12 col-md-6">
        <div class="soft-card shadow-sm h-100">
          <%= render "chats/chat-window", chat: @request.chat %>
        </div>
      </div>
    </div>
  </div>
</div>