config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"

  get 'stripe/oauth', to: 'users#stripe_sign_up'
  devise_for :users
  root to: 'pages#home'

# JOBS

  resources :jobs do
    resources :favourites, only: [:create, :destroy]
    resources :shifts, except: :show do
      resources :orders, only: [:create]
      resources :requests, except: [:show]
      get 'requests/confirmation', to: 'requests#confirmation'
    end
  end
  get 'jobs/:id/close', to: 'jobs#close', as: :job_close
  post 'jobs/sort_pay', to: 'jobs#order_by_pay'
  get 'job/order_by_pay', to: 'jobs#order_by_pay', as: :sort_pay
  get 'job/filter', to: 'jobs#filter', as: :job_filter

# Payments

  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  get '/confirmation_page', to: 'pages#confirmation_page'

# Shifts

  patch '/shifts/close', to: 'shifts#close_shifts', as: :close_shifts
  get 'shifts/:id/users/:user_id/offers/new', to: 'offers#new', as: :new_shift_offer
  post 'shifts/:id/users/:user_id/offers', to: 'offers#create', as: :create_shift_offer
  post 'shifts/:shift_id/reviews', to: 'reviews#create', as: :shift_reviews
  resources :shifts, only: :show

# Offers

  resources :offers, only: :show
  patch 'offers/:id/accept_offer', to: 'shifts#accept_offer', as: 'accept_offer'

# Requests

  resources :requests, only: [:show] do
    resources :chats, only: [:create]
  end
  patch 'requests/:id/accept_request', to: 'shifts#accept_request', as: 'accept_request'

# Applications

  get '/active_applications', to: 'requests#active_applications', as: :active_applications

# Users

  get 'users/:id/offers/select', to: 'offers#select', as: :new_user_offer
  resources :users, only: [:edit, :update]
  get 'user/search', to: 'users#filter', as: :users_filter
  get 'user/sort_score', to: 'users#order_by_score', as: :users_sort_score

  get '/employees', to: 'users#index', as: :users

# Reviews

  get '/reviews', to: 'reviews#review_dashboard', as: :review_dashboard

# Dashboard

  get 'dashboard_employer/closed_jobs', to: 'jobs#closed_jobs', as: :closed_jobs
  get 'dashboard_employer/listed_jobs', to: 'jobs#listed_jobs', as: :listed_jobs
  get '/dashboard_employer', to: 'pages#dashboard_employer'

  get '/dashboard', to: 'pages#dashboard'
  get 'dashboard/pending', to: 'requests#pending_requests', as: 'pending_requests'
  get 'dashboard/upcoming', to: 'shifts#upcoming_shifts', as: 'upcoming_shifts'
  get 'dashboard/historic', to: 'shifts#historic_shifts', as: 'historic_shifts'
  get 'dashboard/favourites', to: 'favourites#index', as: 'favourites'
  get '/dashboard/chats/:id', to: 'chats#inbox_show', as: :dashboard_chat


# Chat

  resources :chats, except: :create do
    resources :messages
  end
  get '/inbox', to: 'chats#inbox', as: :inbox


  # authenticate :user, lambda { |u| u.admin } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :shift
  belongs_to :request
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def select
    @user = User.find(params[:id])
    @offer = Offer.new

    authorize @offer
  end

  def show
    @offer = Offer.find(params[:id])
    @request = @offer.request

    authorize @offer
  end

  def new
    @shift = Shift.find(params[:id])
    @user = User.find(params[:user_id])
    @offer = Offer.new

    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = User.find(params[:user_id])
    @offer.shift = Shift.find(params[:id])
    request = Request.new(user: @offer.user, shift: @offer.shift, content: @offer.content)
    @offer.request = request
    authorize @offer
    if @offer.save
      @chat = Chat.new

      if request.save
        @chat.request = request
        @chat.employee = @offer.user
        @chat.employer = @offer.shift.job.user

        if @chat.save
          @message = Message.new
          @message.chat = @chat
          @message.content = @offer.content
          @message.user = @chat.employer
          if @message.save
            sleep 3
            redirect_to dashboard_employer_path(current_user)
          end
        else
          render :new
        end
      else
        render :new
      end
    else

      render :new
    end
  end





  def add_job_to_offer

  end

  private

  def offer_params
    params.require(:offer).permit(:content, :shift_id, :user_id)
  end
end

app/views/offers/new.html.erb
<div class="container confirmation-page">
  <h2 class="mt-2"><i class="fas fa-arrow-right"></i> </h2><br>
  <h2>Approach <%= @user.first_name %> for: <%= @shift.job.title %></h2>
  <div class="row">
    <div class="col-lg-6 col-12 mb-3">
      <%= render '/users/shared/profile-card', user: @user, profile: true %>
    </div>
    <div class="col-12 col-lg-6 mb-3">

        <div class="dropdown-item message-submission">
          <div class="p-2 border-bottom">
            <div class="p-1 d-flex justify-content-between">
              <p><%= Time.parse(@shift&.start_time)&.strftime("%e %b") %></p>
              <p><%= Time.parse(@shift&.start_time)&.strftime("%k:%M") %> to <%= Time.parse(@shift&.end_time)&.strftime("%k:%M") %></p>
            </div>
            <div class="p-1 d-flex justify-content-between">
              <p><%= humanized_money_with_symbol(@shift.price) %>/h</p>
            </div>
          </div>
        </div>


      <%= simple_form_for  [@shift, @user, @offer], url: create_shift_offer_path(@shift, @user) do |f| %>
        <%= f.input :content, label_html: { class: "content-label" }, input_html: { class: "confirm-page-box" } %>
        <%= f.button :submit, "Send Offer", class: "btn btn-bw", id: "employee-apply-sweetalert" %>
      <% end %>

    </div>


  </div>
</div>

app/views/offers/select.html.erb
<div class="container confirmation-page">
  <h2 class="mt-2"><i class="fas fa-arrow-right"></i> </h2><br>
  <div class="row">
    <div class="col-6">
      <h2>Which shift are you offering to <%= @user.first_name %>?</h2>


      <% current_user.jobs.each do |job| %>

          <div class="py-2 dropdown">
            <% shifts = job.shifts.reject { |shift| shift.completed || shift.user || Time.parse(shift.start_time) < Time.now}  %>
            <% num_shifts = shifts.length %>
            <div class="dropdown-toggle btn btn-bw collapsible active">
              <%= job.title %>
            </div>
            <div class="content-collapse">
              <% shifts.sort_by { |shift| shift.start_time }.each do |shift| %>
                <% unless shift.user || shift.completed %>
                  <% if Time.parse(shift.start_time) > Time.now %>
                    <div class="dropdown-item message-submission">
                      <div class="p-2 border-bottom">
                        <div class="p-1 d-flex justify-content-between">
                          <p><%= Time.parse(shift&.start_time)&.strftime("%e %b") %></p>
                          <p><%= Time.parse(shift&.start_time)&.strftime("%k:%M") %> to <%= Time.parse(shift&.end_time)&.strftime("%k:%M") %></p>
                        </div>
                        <div class="p-1 d-flex justify-content-between">
                          <p><%= humanized_money_with_symbol(shift.price) %>/h</p>
                          <%= link_to "Select shift", new_shift_offer_path(shift, @user),  class: "btn btn-sign-up" %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
      <% end %>

    </div>
    <div class="col-6">
      <%= render '/users/shared/profile-card', user: @user, profile: true %>
    </div>


  </div>
</div>

app/views/offers/show.html.erb
<% user = @offer.shift.job.user %>
<% shift = @offer.shift %>

  <div class="container pt-3">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <%= link_to "", pending_requests_path, class: "btn btn-primary fas fa-arrow-left" %>

      </div>
    </nav>
    <div class="d-flex justify-content-around align-items-top m-3">
      <h1>Offer from <%= user.first_name.capitalize %></h1>
      <%= link_to "Accept Offer", accept_offer_path(@offer), method: :patch, class: "btn btn-bw mb-2" %>

    </div>
    <div class="row">




      <div class="col-12 col-md-6 mb-2">


        <%= render 'shifts/shared/shift-card-employee', shift: shift, user: user %>


        <%= render 'users/shared/profile-card', user: user %>
      </div>

      <div class="col-12 col-md-6">
        <div class="m-2 card">
          <%= render "chats/chat-window", chat: @request.chat %>
        </div>
      </div>

    </div>

  </div>
  <div class="empty_space"></div>